title: "IEEDO"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
search_enabled: true
baseurl: "/IEEDO"
url: "http://vgwb.github.io"
logo: "/assets/img/IEEDO_icon.webp"

aux_links:
  "Go to GitHub Project >":
    - "https://github.com/vgwb/IEEDO"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/vgwb/IEEDO" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
